public class Apexset {
    
    public void set1(){
        SEt <string> set_name = new set <string>();
        set_name.add(' abc ');
        set_name.add(' def ');
        set_name.add(' ghi ');
        set_name.add(' abc ');
        set_name.add(' jkl ');
        set_name.add(' abc ');
        set_name.add(' mno ');
        set_name.add(' pqr ');
        set_name.add(' stu ');
        set_name.add(' vwx ');
        System.debug(set_name);
        System.debug(set_name.size());
    }

}